In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [61]:
# customer info dataset
info_df = pd.read_csv(r"C:\Users\USER\Documents\TS Academy - Data Science\bank churn\banking 3\Customer_Info.csv")
info_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customer_id           7043 non-null   object
 1   gender                7043 non-null   object
 2   age                   7043 non-null   int64
 3   under_30              7043 non-null   object
 4   senior_citizen        7043 non-null   object
 5   partner               7043 non-null   object
 6   dependents            7043 non-null   object
 7   number_of_dependents  7043 non-null   int64
 8   married               7043 non-null   object
dtypes: int64(2), object(7)
memory usage: 495.3+ KB

In [50]:
# location dataset
location_df = pd.read_csv(r"C:\Users\USER\Documents\TS Academy - Data Science\bank churn\banking 3\Location_Data.csv")
location_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       7043 non-null   object
 1   country           7043 non-null   object
 2   state             7043 non-null   object
 3   city              7043 non-null   object
 4   zip_code          7043 non-null   int64
 5   total_population  7043 non-null   int64
 6   latitude          7043 non-null   float64
 7   longitude         7043 non-null   float64
dtypes: float64(2), int64(2), object(4)
memory usage: 440.3+ KB

In [51]:
# online services dataset
online_df = pd.read_csv(r"C:\Users\USER\Documents\TS Academy - Data Science\bank churn\banking 3\Online_Services.csv")
online_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customer_id           7043 non-null   object
 1   phone_service         7043 non-null   object
 2   internet_service      7043 non-null   object
 3   online_security       7043 non-null   object
 4   online_backup         7043 non-null   object
 5   device_protection     7043 non-null   object
 6   premium_tech_support  7043 non-null   object
 7   streaming_tv          7043 non-null   object
 8   streaming_movies      7043 non-null   object
 9   streaming_music       7043 non-null   object
 10  internet_type         5517 non-null   object
dtypes: object(11)
memory usage: 605.4+ KB

In [52]:
# payment info dataset
payment_df = pd.read_csv(r"C:\Users\USER\Documents\TS Academy - Data Science\bank churn\banking 3\Payment_Info.csv")
payment_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 11 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   customer_id                        7043 non-null   object
 1   contract                           7043 non-null   object
 2   paperless_billing                  7043 non-null   object
 3   payment_method                     7043 non-null   object
 4   monthly_ charges                   7043 non-null   float64
 5   avg_monthly_long_distance_charges  7043 non-null   float64
 6   total_charges                      7043 non-null   float64
 7   total_refunds                      7043 non-null   float64
 8   total_extra_data_charges           7043 non-null   int64
 9   total_long_distance_charges        7043 non-null   float64
 10  total_revenue                      7043 non-null   float64
dtypes: float64(6), int64(1), object(4)
memory usage: 605.4+ KB

In [53]:
# service options dataset
service_df = pd.read_csv(r"C:\Users\USER\Documents\TS Academy - Data Science\bank churn\banking 3\Service_Options.csv")
service_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              7043 non-null   object
 1   tenure                   7043 non-null   int64
 2   internet_service         7043 non-null   object
 3   phone_service            7043 non-null   object
 4   multiple_lines           7043 non-null   object
 5   avg_monthly_gb_download  7043 non-null   int64
 6   unlimited_data           7043 non-null   object
 7   offer                    3166 non-null   object
 8   referred_a_friend        7043 non-null   object
 9   number_of_referrals      7043 non-null   int64
dtypes: int64(3), object(7)
memory usage: 550.4+ KB

In [54]:
# status analysis dataset
status_df = pd.read_csv(r"C:\Users\USER\Documents\TS Academy - Data Science\bank churn\banking 3\Status_Analysis.csv")
status_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         7043 non-null   object
 1   satisfaction_score  7043 non-null   int64
 2   cltv                7043 non-null   int64
 3   customer_status     7043 non-null   object
 4   churn_score         7043 non-null   int64
 5   churn_label         7043 non-null   object
 6   churn_value         7043 non-null   int64
 7   churn_category      7043 non-null   object
 8   churn_reason        1869 non-null   object
dtypes: int64(4), object(5)
memory usage: 495.3+ KB

In [69]:
# checking for duplicated entries
# info_df['customer_id'].duplicated().sum()
# location_df['customer_id'].duplicated().sum()
# online_df['customer_id'].duplicated().sum()
# payment_df['customer_id'].duplicated().sum()
# service_df['customer_id'].duplicated().sum()
# status_df['customer_id'].duplicated().sum()

In [81]:
# checking for null values
# info_df.isna().sum()
# location_df.isna().sum()
# online_df.isna().sum()
# payment_df.isna().sum()
# service_df.isna().sum()
# status_df.isna().sum()

customer_id              0
satisfaction_score       0
cltv                     0
customer_status          0
churn_score              0
churn_label              0
churn_value              0
churn_category           0
churn_reason          5174
dtype: int64

In [82]:
status_df['churn_reason'].unique()

array([nan, 'Competitor had better devices', 'Product dissatisfaction',
       'Network reliability', 'Limited range of services',
       'Competitor made better offer', "Don't know",
       'Long distance charges', 'Attitude of service provider',
       'Attitude of support person',
       'Competitor offered higher download speeds',
       'Competitor offered more data',
       'Lack of affordable download/upload speed', 'Deceased', 'Moved',
       'Service dissatisfaction', 'Price too high',
       'Lack of self-service on Website',
       'Poor expertise of online support', 'Extra data charges',
       'Poor expertise of phone support'], dtype=object)

In [83]:
# MERGING ALL TABLES INTO ONE
main_df = info_df

In [84]:
main_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customer_id           7043 non-null   object
 1   gender                7043 non-null   object
 2   age                   7043 non-null   int64
 3   under_30              7043 non-null   object
 4   senior_citizen        7043 non-null   object
 5   partner               7043 non-null   object
 6   dependents            7043 non-null   object
 7   number_of_dependents  7043 non-null   int64
 8   married               7043 non-null   object
dtypes: int64(2), object(7)
memory usage: 495.3+ KB

In [85]:
main_df = main_df.merge(location_df, on="customer_id", how="left")

In [86]:
main_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customer_id           7043 non-null   object
 1   gender                7043 non-null   object
 2   age                   7043 non-null   int64
 3   under_30              7043 non-null   object
 4   senior_citizen        7043 non-null   object
 5   partner               7043 non-null   object
 6   dependents            7043 non-null   object
 7   number_of_dependents  7043 non-null   int64
 8   married               7043 non-null   object
 9   country               7043 non-null   object
 10  state                 7043 non-null   object
 11  city                  7043 non-null   object
 12  zip_code              7043 non-null   int64
 13  total_population      7043 non-null   int64
 14  latitude              7043 non-null   float64
 15  longitude             7043 non-null   float64
dtypes: float64(2), int64(4), object(10)
memory usage: 880.5+ KB

In [87]:
main_df = main_df.merge(online_df, on="customer_id", how="left")

In [88]:
main_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 26 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customer_id           7043 non-null   object
 1   gender                7043 non-null   object
 2   age                   7043 non-null   int64
 3   under_30              7043 non-null   object
 4   senior_citizen        7043 non-null   object
 5   partner               7043 non-null   object
 6   dependents            7043 non-null   object
 7   number_of_dependents  7043 non-null   int64
 8   married               7043 non-null   object
 9   country               7043 non-null   object
 10  state                 7043 non-null   object
 11  city                  7043 non-null   object
 12  zip_code              7043 non-null   int64
 13  total_population      7043 non-null   int64
 14  latitude              7043 non-null   float64
 15  longitude             7043 non-null   float64
 16  phone_service         7043 non-null   object
 17  internet_service      7043 non-null   object
 18  online_security       7043 non-null   object
 19  online_backup         7043 non-null   object
 20  device_protection     7043 non-null   object
 21  premium_tech_support  7043 non-null   object
 22  streaming_tv          7043 non-null   object
 23  streaming_movies      7043 non-null   object
 24  streaming_music       7043 non-null   object
 25  internet_type         5517 non-null   object
dtypes: float64(2), int64(4), object(20)
memory usage: 1.4+ MB

In [89]:
main_df = main_df.merge(payment_df, on="customer_id", how="left")

In [90]:
main_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 36 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   customer_id                        7043 non-null   object
 1   gender                             7043 non-null   object
 2   age                                7043 non-null   int64
 3   under_30                           7043 non-null   object
 4   senior_citizen                     7043 non-null   object
 5   partner                            7043 non-null   object
 6   dependents                         7043 non-null   object
 7   number_of_dependents               7043 non-null   int64
 8   married                            7043 non-null   object
 9   country                            7043 non-null   object
 10  state                              7043 non-null   object
 11  city                               7043 non-null   object
 12  zip_code                           7043 non-null   int64
 13  total_population                   7043 non-null   int64
 14  latitude                           7043 non-null   float64
 15  longitude                          7043 non-null   float64
 16  phone_service                      7043 non-null   object
 17  internet_service                   7043 non-null   object
 18  online_security                    7043 non-null   object
 19  online_backup                      7043 non-null   object
 20  device_protection                  7043 non-null   object
 21  premium_tech_support               7043 non-null   object
 22  streaming_tv                       7043 non-null   object
 23  streaming_movies                   7043 non-null   object
 24  streaming_music                    7043 non-null   object
 25  internet_type                      5517 non-null   object
 26  contract                           7043 non-null   object
 27  paperless_billing                  7043 non-null   object
 28  payment_method                     7043 non-null   object
 29  monthly_ charges                   7043 non-null   float64
 30  avg_monthly_long_distance_charges  7043 non-null   float64
 31  total_charges                      7043 non-null   float64
 32  total_refunds                      7043 non-null   float64
 33  total_extra_data_charges           7043 non-null   int64
 34  total_long_distance_charges        7043 non-null   float64
 35  total_revenue                      7043 non-null   float64
dtypes: float64(8), int64(5), object(23)
memory usage: 1.9+ MB

In [91]:
main_df = main_df.merge(service_df, on="customer_id", how="left")

In [92]:
main_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 45 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   customer_id                        7043 non-null   object
 1   gender                             7043 non-null   object
 2   age                                7043 non-null   int64
 3   under_30                           7043 non-null   object
 4   senior_citizen                     7043 non-null   object
 5   partner                            7043 non-null   object
 6   dependents                         7043 non-null   object
 7   number_of_dependents               7043 non-null   int64
 8   married                            7043 non-null   object
 9   country                            7043 non-null   object
 10  state                              7043 non-null   object
 11  city                               7043 non-null   object
 12  zip_code                           7043 non-null   int64
 13  total_population                   7043 non-null   int64
 14  latitude                           7043 non-null   float64
 15  longitude                          7043 non-null   float64
 16  phone_service_x                    7043 non-null   object
 17  internet_service_x                 7043 non-null   object
 18  online_security                    7043 non-null   object
 19  online_backup                      7043 non-null   object
 20  device_protection                  7043 non-null   object
 21  premium_tech_support               7043 non-null   object
 22  streaming_tv                       7043 non-null   object
 23  streaming_movies                   7043 non-null   object
 24  streaming_music                    7043 non-null   object
 25  internet_type                      5517 non-null   object
 26  contract                           7043 non-null   object
 27  paperless_billing                  7043 non-null   object
 28  payment_method                     7043 non-null   object
 29  monthly_ charges                   7043 non-null   float64
 30  avg_monthly_long_distance_charges  7043 non-null   float64
 31  total_charges                      7043 non-null   float64
 32  total_refunds                      7043 non-null   float64
 33  total_extra_data_charges           7043 non-null   int64
 34  total_long_distance_charges        7043 non-null   float64
 35  total_revenue                      7043 non-null   float64
 36  tenure                             7043 non-null   int64
 37  internet_service_y                 7043 non-null   object
 38  phone_service_y                    7043 non-null   object
 39  multiple_lines                     7043 non-null   object
 40  avg_monthly_gb_download            7043 non-null   int64
 41  unlimited_data                     7043 non-null   object
 42  offer                              3166 non-null   object
 43  referred_a_friend                  7043 non-null   object
 44  number_of_referrals                7043 non-null   int64
dtypes: float64(8), int64(8), object(29)
memory usage: 2.4+ MB

In [93]:
main_df = main_df.merge(status_df, on="customer_id", how="left")

In [94]:
main_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 53 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   customer_id                        7043 non-null   object
 1   gender                             7043 non-null   object
 2   age                                7043 non-null   int64
 3   under_30                           7043 non-null   object
 4   senior_citizen                     7043 non-null   object
 5   partner                            7043 non-null   object
 6   dependents                         7043 non-null   object
 7   number_of_dependents               7043 non-null   int64
 8   married                            7043 non-null   object
 9   country                            7043 non-null   object
 10  state                              7043 non-null   object
 11  city                               7043 non-null   object
 12  zip_code                           7043 non-null   int64
 13  total_population                   7043 non-null   int64
 14  latitude                           7043 non-null   float64
 15  longitude                          7043 non-null   float64
 16  phone_service_x                    7043 non-null   object
 17  internet_service_x                 7043 non-null   object
 18  online_security                    7043 non-null   object
 19  online_backup                      7043 non-null   object
 20  device_protection                  7043 non-null   object
 21  premium_tech_support               7043 non-null   object
 22  streaming_tv                       7043 non-null   object
 23  streaming_movies                   7043 non-null   object
 24  streaming_music                    7043 non-null   object
 25  internet_type                      5517 non-null   object
 26  contract                           7043 non-null   object
 27  paperless_billing                  7043 non-null   object
 28  payment_method                     7043 non-null   object
 29  monthly_ charges                   7043 non-null   float64
 30  avg_monthly_long_distance_charges  7043 non-null   float64
 31  total_charges                      7043 non-null   float64
 32  total_refunds                      7043 non-null   float64
 33  total_extra_data_charges           7043 non-null   int64
 34  total_long_distance_charges        7043 non-null   float64
 35  total_revenue                      7043 non-null   float64
 36  tenure                             7043 non-null   int64
 37  internet_service_y                 7043 non-null   object
 38  phone_service_y                    7043 non-null   object
 39  multiple_lines                     7043 non-null   object
 40  avg_monthly_gb_download            7043 non-null   int64
 41  unlimited_data                     7043 non-null   object
 42  offer                              3166 non-null   object
 43  referred_a_friend                  7043 non-null   object
 44  number_of_referrals                7043 non-null   int64
 45  satisfaction_score                 7043 non-null   int64
 46  cltv                               7043 non-null   int64
 47  customer_status                    7043 non-null   object
 48  churn_score                        7043 non-null   int64
 49  churn_label                        7043 non-null   object
 50  churn_value                        7043 non-null   int64
 51  churn_category                     7043 non-null   object
 52  churn_reason                       1869 non-null   object
dtypes: float64(8), int64(12), object(33)
memory usage: 2.8+ MB

In [103]:
# NOTICED IDENTICAL TABLE COLUMNS, CHECKING IF THE ENTRIES ARE IDENTICAL AND REQUIRES ONE BEING DROPPED
(main_df['phone_service_x'] == main_df['phone_service_y']).mean()

1.0

In [99]:
# main_df['phone_service_x'].value_counts()
main_df['phone_service_y'].value_counts()

phone_service_y
Yes    6361
No      682
Name: count, dtype: int64

In [100]:
(main_df['internet_service_x'] == main_df['internet_service_y']).mean()

1.0

In [102]:
main_df['internet_service_x'].value_counts()
# main_df['internet_service_y'].value_counts()

internet_service_x
Yes    5517
No     1526
Name: count, dtype: int64

In [104]:
main_df = main_df.drop(columns=['phone_service_x'])

In [105]:
main_df = main_df.rename(columns={'phone_service_y' : 'phone_service'})

In [106]:
main_df = main_df.drop(columns=['internet_service_x'])

In [107]:
main_df = main_df.rename(columns={'internet_service_y' : 'internet_service'})

In [108]:
main_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 51 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   customer_id                        7043 non-null   object
 1   gender                             7043 non-null   object
 2   age                                7043 non-null   int64
 3   under_30                           7043 non-null   object
 4   senior_citizen                     7043 non-null   object
 5   partner                            7043 non-null   object
 6   dependents                         7043 non-null   object
 7   number_of_dependents               7043 non-null   int64
 8   married                            7043 non-null   object
 9   country                            7043 non-null   object
 10  state                              7043 non-null   object
 11  city                               7043 non-null   object
 12  zip_code                           7043 non-null   int64
 13  total_population                   7043 non-null   int64
 14  latitude                           7043 non-null   float64
 15  longitude                          7043 non-null   float64
 16  online_security                    7043 non-null   object
 17  online_backup                      7043 non-null   object
 18  device_protection                  7043 non-null   object
 19  premium_tech_support               7043 non-null   object
 20  streaming_tv                       7043 non-null   object
 21  streaming_movies                   7043 non-null   object
 22  streaming_music                    7043 non-null   object
 23  internet_type                      5517 non-null   object
 24  contract                           7043 non-null   object
 25  paperless_billing                  7043 non-null   object
 26  payment_method                     7043 non-null   object
 27  monthly_ charges                   7043 non-null   float64
 28  avg_monthly_long_distance_charges  7043 non-null   float64
 29  total_charges                      7043 non-null   float64
 30  total_refunds                      7043 non-null   float64
 31  total_extra_data_charges           7043 non-null   int64
 32  total_long_distance_charges        7043 non-null   float64
 33  total_revenue                      7043 non-null   float64
 34  tenure                             7043 non-null   int64
 35  internet_service                   7043 non-null   object
 36  phone_service                      7043 non-null   object
 37  multiple_lines                     7043 non-null   object
 38  avg_monthly_gb_download            7043 non-null   int64
 39  unlimited_data                     7043 non-null   object
 40  offer                              3166 non-null   object
 41  referred_a_friend                  7043 non-null   object
 42  number_of_referrals                7043 non-null   int64
 43  satisfaction_score                 7043 non-null   int64
 44  cltv                               7043 non-null   int64
 45  customer_status                    7043 non-null   object
 46  churn_score                        7043 non-null   int64
 47  churn_label                        7043 non-null   object
 48  churn_value                        7043 non-null   int64
 49  churn_category                     7043 non-null   object
 50  churn_reason                       1869 non-null   object
dtypes: float64(8), int64(12), object(31)
memory usage: 2.7+ MB

In [110]:
(main_df['partner'] == main_df['married']).mean()

1.0

In [111]:
main_df = main_df.drop(columns = 'married')

In [146]:
# percentage of people that have churned
label = main_df.groupby('churn_label')[['churn_value']].count()
get_yes = label.loc['Yes']['churn_value']
no_percentage = (get_yes / len(main_df)) * 100
print(f"Total number of people who churned are -> {no_percentage}%")
# print(f"Total rounded number of people who churned are -> {no_percentage.round()}%")

Total number of people who churned are -> 26.536987079369588%

In [174]:
# biggest reasons why people churn
reason = main_df.groupby('churn_reason')[['churn_value']].count()
greater_than_100 = reason['churn_value'] > 100
highest_reason = reason[greater_than_100]
highest_reason

                               churn_value
churn_reason
Attitude of support person             220
Competitor had better devices          313
Competitor made better offer           311
Competitor offered more data           117
Don't know                             130

In [279]:
# Which churn categories contribute most to customer loss?
churned_df = main_df[main_df['churn_value'] == 1]
categories = churned_df.groupby('churn_category')['churn_value'].count()
categories

churn_category
Attitude           314
Competitor         841
Dissatisfaction    303
Other              200
Price              211
Name: churn_value, dtype: int64

In [280]:
# What is the percentage of customers that Churned, Stayed, or Newly Joined?
# status = main_df.groupby('customer_status')['churn_value'].count()
status = main_df['customer_status'].value_counts()
percentage = (status / len(main_df)) * 100
percentage

customer_status
Stayed     67.016896
Churned    26.536987
Joined      6.446117
Name: count, dtype: float64

In [281]:
# What is the distribution of churn_score?
distribution_churn_score = main_df['churn_score'].value_counts()
distribution_churn_score

churn_score
91    202
80    150
71    148
77    145
67    142
     ...
88     33
9       3
8       2
7       2
5       1
Name: count, Length: 81, dtype: int64

In [282]:
# Are higher churn scores actually linked to churn_value = 1?
check_score = main_df.groupby('churn_score')[['churn_value']].mean()
check_score

             churn_value
churn_score
5                    0.0
7                    0.0
8                    0.0
9                    0.0
20                   0.0
...                  ...
92                   1.0
93                   1.0
94                   1.0
95                   1.0
96                   1.0

[81 rows x 1 columns]

In [283]:
# What churn_score range is the danger zone (where churn rate becomes high)?
churn_zone = main_df.groupby('churn_score')[['churn_value']].mean()
danger_zone = (churn_zone  * 100)
danger_zone

             churn_value
churn_score
5                    0.0
7                    0.0
8                    0.0
9                    0.0
20                   0.0
...                  ...
92                 100.0
93                 100.0
94                 100.0
95                 100.0
96                 100.0

[81 rows x 1 columns]

In [284]:
# Where does churn rate starts rising sharply? 
rising_point = danger_zone['churn_value'].diff()
rising_point[rising_point  > 10]

churn_score
65    39.259259
69    10.590062
81    64.000000
Name: churn_value, dtype: float64

In [285]:
# what is your trigger point?
trigger_point = rising_point[rising_point  > 10]
print(f"The trigger point is {trigger_point.index[0]}")

The trigger point is 65

In [ ]:
# What is the revenue loss from churned customers?